latest @dev/fun -> staging
syrus-bot/syrus-bot pull request #40
Opened 2020-12-19 04:36 UTC by mynameismax

2020-12-19 18:49 UTC, Nytelife26 requested changes
Updating `package-lock.json` and `package.json` are out of scope for this branch. Aside from that, all is fine, so long as you resolve LGTM concerns and implement the advice contained in this review.

2020-12-19 18:49 UTC, lveneris commented on package.json
> +		"discord.js-minesweeper": "^1.0.6",
Having reviewed the code involved in this new dependency, it seems to be overly inefficient, clunky, and go against Syrus design philosophy. Would it be possible to consider adding our own implementation instead?

2020-12-19 18:49 UTC, lveneris commented on src/commands/Fun/8ball.js
> +const answers = [
Correct the typo on line 25 ("certian" -> "certain") and change `answers` to `ANSWERS` to follow our [naming conventions](https://github.com/syrus-bot/community/blob/master/CONTRIBUTING.md#naming-conventions).

2020-12-19 18:49 UTC, lveneris commented on src/commands/Fun/clap.js
> +function clapWord(word) {
This function is redundant - it can be merged with `clapMessage` by adding a check to see how many words are in the input string and enacting the resulting behaviour of `clapWord` depending on the truth of that condition.

2020-12-19 18:49 UTC, lveneris commented on src/commands/Fun/clap.js
> +		if (!/\s/.test(messageToClap.value.trim())) {
As aforementioned, this check should be done in the function itself, and then this block of repeated code on conditionality can be removed.

2020-12-19 18:49 UTC, lveneris commented on src/commands/Fun/dadjoke.js
> +			"user-agent": "Syrus Discord Bot",
Change this to the Syrus standardised UA.

2020-12-19 18:49 UTC, lveneris commented on src/commands/Fun/dadjoke.js
> +	return json;
Implement error handling for if it could not reach the API, could not find a joke, etc.

2020-12-19 18:49 UTC, Nytelife26 commented on src/commands/Fun/minesweeper.js
> +/* const game = await genGame(difficultyChoice);
Dev comments should not be left upstream for staging to next release unless they are TODOs, which are passable.

2020-12-19 18:49 UTC, Nytelife26 commented on src/commands/Fun/minesweeper.js
> +		).then(async (msg) => {
Because of await, this is not needed. You can use the constant `choiceMessage` you created to run the next block.

2020-12-19 18:49 UTC, Nytelife26 commented on src/commands/Fun/owoify.js
> +		.replace(/(n)([aeiou])/gi, "$1y$2") // eslint-disable-line prefer-named-capture-group
You may commit disabling that rule to `.eslintrc.json`, as I have determined after investigating it is unnecessary. I will file an issue regarding standardised settings for all lint rules after this review.

2020-12-20 05:29 UTC, Nytelife26 commented on src/commands/Fun/owoify.js
> +		.replace(/(n)([aeiou])/gi, "$1y$2") // eslint-disable-line prefer-named-capture-group
Resolved in #41.

2020-12-24 21:46 UTC, Nytelife26 commented
Placing this on hold temporarily while changes are made.

2020-12-25 18:55 UTC, Nytelife26 approved these changes
All changes implemented, now ready for merge upstream.

2020-12-25 18:57 UTC, merged

2021-01-17 03:48 UTC, Nytelife26 commented
:tada: This PR is included in version 2.0.0-staging.1 :tada:

The release is available on [GitHub release](https://github.com/syrus-bot/syrus-bot/releases/tag/v2.0.0-staging.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-01-17 17:41 UTC, Nytelife26 commented
:tada: This PR is included in version 2.0.0-staging.1 :tada:

The release is available on [GitHub release](https://github.com/syrus-bot/syrus-bot/releases/tag/v2.0.0-staging.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: